const symbolsToIndex = [
  '!',
  '"',
  '#',
  '$',
  '%',
  '&',
  "'",
  '(',
  ')',
  '*',
  '+',
  ',',
  '-',
  '.',
  '/',
  ':',
  ';',
  '<',
  '=',
  '>',
  '?',
  '@',
  '[',
  '\\',
  ']',
  '^',
  '_',
  '`',
  '{',
  '|',
  '}',
  '~',
];

export default [
  {
    name: 'searches',
    fields: [
      { name: 'id', type: 'string' },
      {
        name: 'query',
        type: 'string',
        infix: true,
        sort: true, // ✅ makes alphabetical sorting possible
      },
      { name: 'searchCount', type: 'int32' },
    ],
    symbols_to_index: symbolsToIndex,
    default_sorting_field: 'searchCount',
  },
  {
    name: 'users',
    fields: [
      { name: 'id', type: 'string', facet: true },
      { name: 'username', type: 'string' },
      { name: 'name', type: 'string' },
      { name: 'createdAt', type: 'int64' },
    ],
    symbols_to_index: symbolsToIndex,
  },
  {
    name: 'contents',
    fields: [
      { name: 'id', type: 'string' },
      { name: 'user', type: 'string', facet: true },
      { name: 'description', type: 'string' },
      {
        name: 'media',
        type: 'string',
      },
      { name: 'createdAt', type: 'int64' },
    ],
    symbols_to_index: symbolsToIndex,
  },
  {
    name: 'reels',
    fields: [
      { name: 'id', type: 'string' },
      { name: 'user', type: 'string', facet: true },
      { name: 'description', type: 'string' },
      {
        name: 'src',
        type: 'string',
      },
      { name: 'createdAt', type: 'int64' },
    ],
    symbols_to_index: symbolsToIndex,
  },
];
